name = "TensorAlgebra"
uuid = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"
version = "0.7.6"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FunctionImplementations = "7c7cc465-9c6a-495f-bdd1-f42428e86d0c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixAlgebraKit = "6c742aac-3347-4629-af66-fc926824e5e4"
StridedViews = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[weakdeps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[extensions]
TensorAlgebraBlockArraysExt = "BlockArrays"
TensorAlgebraGPUArraysCoreExt = "GPUArraysCore"
TensorAlgebraMooncakeExt = "Mooncake"
TensorAlgebraTensorOperationsExt = "TensorOperations"

[compat]
BlockArrays = "1.7.2"
EllipsisNotation = "1.8"
FunctionImplementations = "0.3.1, 0.4"
GPUArraysCore = "0.2"
LinearAlgebra = "1.10"
MatrixAlgebraKit = "0.2, 0.3, 0.4, 0.5, 0.6"
Mooncake = "0.4.202, 0.5"
StridedViews = "0.4.1"
TensorOperations = "5"
TupleTools = "1.6"
TypeParameterAccessors = "0.2.1, 0.3, 0.4"
julia = "1.10"
